### Updates an existing user entity
PUT http://localhost:4000/users/123e4567-e89b-12d3-a456-426614174000
Content-Type: application/json

{
  "firstName": "John Updated",
  "lastName": "Doe",
  "email": "johndoe2@gmail.com",
  "phoneNumber": "6173456745",
  "address": "123 main street",
  "city": "Boston",
  "state": "MA",
  "country": "USA",
  "dateOfBirth": "1993-06-18"
}